### ISSUE TITLE
issue 1

### ISSUE THREAD

**Issue by ADcountdown** [Evlpsrfc/electromobile#1]
很棒的项目！用来找充电位很方便
----------------------------
问题：
网址是变动了？2022/10/19无法访问http://10.20.7.127:5000/

建议：
网站中可否在对应的充电桩中增加 “最近更新时间"，这样配合付费时间就可以知道自己充电车是不是被人拔了

感谢！

**Comment by Evlpsrfc** [comment]
谢谢你认可我的工作，但是很抱歉，这个项目已经死了，10月18号老师示意我关停网站，并且把原本给的后台账号也注销了，至今原因不明。
